; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "SpeeDReaD"
#define MyAppVersion "2.2.2"
#define MyAppPublisher "Wilson's Widgets"
#define MyAppURL "https://sourceforge.net/projects/SpeeDReaD/"
#define MyAppExeName "SpeeDReaD.exe"
#define ProjectDir "X:\Documents\Python Workspace\SpeeDReaD"
#define OutputDir "C:\Users\jeremy\Desktop\output"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A016155A-18AC-4E64-B8F3-C2835848B23B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
LicenseFile={#OutputDir}\SpeeDReaD\_internal\resources\gpl-3.0.rtf
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest  
WizardImageFile={#ProjectDir}\resources\installImage.bmp
WizardSmallImageFile = X:\Documents\Python Workspace\SpeeDReaD\resources\installImageSmall.bmp
PrivilegesRequiredOverridesAllowed=dialog
OutputDir={#OutputDir}\SpeeDReaD\installer
OutputBaseFilename=Setup_SpeeDReaD_v.{#MyAppVersion}
SetupIconFile={#ProjectDir}\resources\sr_logo.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#OutputDir}\SpeeDReaD\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#OutputDir}\SpeeDReaD\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#OutputDir}\SpeeDReaD\_internal\README.html"; DestDir: "{app}"; Flags: isreadme
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

